### ISSUE TITLE
Encode Files CBR fixed to 31kbs , can not be change

### ISSUE THREAD

**Issue by Harvey365** [vividos/winLAME#10]
I tried to convert 320kbps mp3 files to 128kbps wma file and I changed constant bitrate to 128kbps, but it always output  31kbps wma files at last. What should I do ? Thank you !

**Comment by vividos** [comment]
I'll have a look if the bitrate parameter is transferred correctly to the WMA encoder

**Comment by vividos** [comment]
This is fixed in the latest version, starting from 2.23.0.138. You can download the version from the latest AppVeyor build: https://ci.appveyor.com/project/vividos/winlame/build/artifacts
Thanks for reporting the bug!
