### ISSUE TITLE
Behavior with M3U 

### ISSUE THREAD

**Issue by lowpursuit** [vividos/winLAME#11]
Not sure if this is a bug or not, but if I add a folder with a M3U this happens (see attachment) - And trying to run everything without cleaning up the input files leads to errors -Josh
![delme 1](https://github.com/vividos/winLAME/assets/78461535/b9f799ee-1e8b-4226-8b16-a4856b8659c3)
![delme 2](https://github.com/vividos/winLAME/assets/78461535/0f0a0288-c5d6-40b8-af64-5abc09085ad9)

**Comment by vividos** [comment]
Hi Josh, .m3u files are playlist files and contain the filenames in the proper order to play back. Just add the .m3u file only, and not the whole folder. The errors you get afterwards are likely from encoding the same files twice.
