### ISSUE TITLE
"Eject Disk after reading" ejects after every track.

### ISSUE THREAD

**Issue by Woody-Soft** [vividos/winLAME#12]
The new option to "Eject disk after reading" is called after reading each track instead of after finishing all processing.
![image](https://github.com/user-attachments/assets/0cfafa37-c324-4541-81a3-415cf22e5210)
I enabled that option after processing the previous disk CD3, and then the "CD auswerfen showed up after each track-read instead of after "Finished CD". 

It would also be helpful, we we could get a menue-entry in that "Encoding finish action" dropdown list.

**Comment by vividos** [comment]
The latest build 2.24.0.148 fixes the issue. Thanks for reporting it!
