### ISSUE TITLE
libfaac output module produces unusable files with "Main" profile

### ISSUE THREAD

**Issue by stoermelder** [vividos/winLAME#14]
Steps to reproduce
- Select "libfaac" output module
- Select "Custom settings"
- Select "Main" for "AAC object type", leave all other settings unchanged

This creates small files which seem to be unusable.

**Comment by vividos** [comment]
Hi, did you test with the latest build? It should have the best libfaac version. Did you also test with the command line libfaac tool? Does it produce the same files or do they differ?

**Comment by vividos** [comment]
Here's the link to the build: https://ci.appveyor.com/project/vividos/winlame/build/artifacts

**Comment by stoermelder** [comment]
I closed this issue mistakenly.
I tested it with the latest build but it made no difference. I checked the command line tool for libfaac but it does not support setting a different AAC object type.

**Comment by vividos** [comment]
Indeed, I checked the faac source code, and in the command line tool, the `objectType` is set to `LOW` and there's no way to change it:
https://github.com/knik0/faac/blob/1_30/frontend/main.c#L428

And in the GUI tool, it's the only option to select from a combobo:
https://github.com/knik0/faac/blob/1_30/frontend/maingui.c#L340

I will also disable selecting anything other than `LOW`.

**Comment by vividos** [comment]
Fixed in 2.24.0.150 or any later build.

**Comment by vividos** [comment]
Thanks for reporting this issue!
