### ISSUE TITLE
Crash on opening FLAC files

### ISSUE THREAD

**Issue by rfilmyer** [vividos/winLAME#2]
Tried using the software and instantly hit a crash trying to open some FLAC files.

I can provide the files upon request, they also may be associated with the following hash: `CCE242B973F1EBA7831BD7146AE806C5D9504F65`. I loaded the first file that that hash is referencing as well as all of the referenced FLAC files.

I am attaching two memdumps from my crashes. The first is from a single file, and the second is from loading a number of FLAC files at once.

[winlame bugs.zip](https://github.com/vividos/winLAME/files/5527487/winlame.bugs.zip)

This occurs in both the classic and "new" view.

One thing I noticed (check out this screenshot):
![image](https://user-images.githubusercontent.com/5913205/98878917-36c91c80-2452-11eb-9375-b497c7dfd6d5.png)

* The files appear to have an absurd duration sometimes

**Comment by vividos** [comment]
I see that you're still using the 2019 release 1 version. Can you retest the bug with the latest AppVeyor build? Thanks!

**Comment by rfilmyer** [comment]
Build 2.20.0.83 on AppVeyor appears to work fine, program does not crash when loading the same FLAC files, duration fields are normal and conversion works fine.

Self-closing as resolved (working on nightlies)

**Comment by vividos** [comment]
Thanks for the feedback!
