### ISSUE TITLE
Crash while converting wma to mp3

### ISSUE THREAD

**Issue by RocketSurgeonPrime** [vividos/winLAME#3]
multiple program crashes upon use
trying to batch convert wma to mp3 using transparent preset
uploading dump files (mdmp changed to txt to enable uploading)

[winLAME-2021-10-17 20_44_32.txt](https://github.com/vividos/winLAME/files/7361353/winLAME-2021-10-17.20_44_32.txt)
s
[winLAME-2021-10-17 20_46_51.txt](https://github.com/vividos/winLAME/files/7361357/winLAME-2021-10-17.20_46_51.txt)
e

**Comment by vividos** [comment]
Thanks for your bug report! I checked in a change that may fix the issue; could you please try out build 2.21.0.102 (or any later) if it fixes the issue? Thanks!

**Comment by vividos** [comment]
Unfortunately I didn't hear back from you. If the issue still persists with the latest build, please open a new issue. Thanks!
