### ISSUE TITLE
A / (solidus) in a song title will result in creation of subdirectories

### ISSUE THREAD

**Issue by smccrearyx** [vividos/winLAME#4]
Test case CD this was discovered on was Panic at the Disco!   Too Weird To Live, Too Rare To Die!  track#6  
Song is named: Girls/Girls/Boys  
A solution might be to sub it for a Division Slash or some other character.

**Comment by vividos** [comment]
Thanks for your issue, I'll take a look!

**Comment by vividos** [comment]
I just added a bugfix; please check out 2.21.0.103 (or any later) if this fixes your bug. Thanks!

**Comment by vividos** [comment]
Unfortunately I didn't hear back from you. I think the issue is fixed, but there is still a problem in this area of winLAME, please open a new issue. Thanks!
