### ISSUE TITLE
libSndFile preset "FLAC lossless from 16 bit audio" creates 8bit flac-s by default.

### ISSUE THREAD

**Issue by razielanarki** [vividos/winLAME#5]
this setting:
https://github.com/vividos/winLAME/blob/3c95f79a8623c3852bee1ee5b6e1cd32e207e02d/source/presets.xml#L168

causes WinLAME to create 8bit flac-s with the default libSndFile preset (preset: "FLAC lossless from 16 bit audio")

Either the preset name is misleading / should be clarified, or the sub-type setting should be changed to "2".

<br />
<br />
<br />

_**workaround for anyone interested:**_

Changing the sub-type setting to "2", ie:

```xml
    <value name="sndFileSubType">2</value>
```

after installation (in my case, the `presets.xml` was located in "`C:\ProgramData\WinLAME\presets.xml`") makes winlame create 16-bit FLAC files using this preset.

**Comment by vividos** [comment]
Thanks for the issue, I'll have a look!

**Comment by vividos** [comment]
Fixed from build 2.22.0.111 on. Thanks!
