### ISSUE TITLE
The genre field of mp3 always set to Blues

### ISSUE THREAD

**Issue by steelowheel** [vividos/winLAME#6]
I'm with winLAME 2021 Release 1, and just converted some flacs to mp3. It seems the genre field of mp3 files say Blues. The flac files in question don't have genre fields.

**Comment by vividos** [comment]
I'll have a look at the code. Meanwhile you can edit the tags using mp3tag.

**Comment by vividos** [comment]
This is fixed in winLAME 2.23.0.135. You can get the build from the AppVeyor web site.
