### ISSUE TITLE
Support entering disc number and replace %disc% in CD track title

### ISSUE THREAD

**Issue by Woody-Soft** [vividos/winLAME#8]
Could we get a %DiscNumber% (or short: %disc%) Variable for tagging? 
That way we could automatically create folders for a "Multi CD Set"
With that option you could also strip that appended "CDxx" in the title

**Comment by vividos** [comment]
I'll have a look if BassCD can return that value or if it could be an edit field like artist etc. Reading from tags and writing to them should already support the disc number.

**Comment by vividos** [comment]
This is contained in the winLAME 2023 release 1.
