### ISSUE TITLE
Open CD drawer

### ISSUE THREAD

**Issue by Woody-Soft** [vividos/winLAME#9]
Could we get a Toolbar-button for opening the CD-drawer? 
And also an config option "Eject CD after reading" Yes/No ?

**Comment by vividos** [comment]
I'll have a look if the library BassCD supports this. Thanks for the request!

**Comment by vividos** [comment]
This is contained in the winLAME 2023 release 1.

**Comment by Woody-Soft** [comment]
Thank you for this enhancements!
